#! /usr/bin/env python3
# -*- coding:utf-8 -*-

import time
from termcolor import colored

def configs():
    print("\n\n")
    print(colored("##========================================================================##","yellow"))
    print(colored("#                       __ _                            /\/|               #","yellow"))
    print(colored("#                      / _(_)                          |/\/                #","yellow"))
    print(colored("#       ___ ___  _ __ | |_ _  __ _ _   _ _ __ __ _  ___ ___   ___  ___     #","yellow"))
    print(colored("#      / __/ _ \| '_ \|  _| |/ _` | | | | '__/ _` |/ __/ _ \ / _ \/ __|    #","yellow"))
    print(colored("#     | (_| (_) | | | | | | | (_| | |_| | | | (_| | (_| (_) |  __/\__ \    #","yellow"))
    print(colored("#      \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\___\___/ \___||___/    #","yellow"))
    print(colored("#                             __/ |                 )_)                    #","yellow"))
    print(colored("#                            |___/                                         #","yellow"))
    print(colored("##========================================================================##","yellow"))

def logo_relampago_markinhos(objetivo, ativar_todos = False):
    '''
    Função que imprime uma pequena animação no terminal
    '''
    markinhos_on = False
    sinal_on = False
    agradecimentos_on = False
    time_regulado = 0.1

    if ativar_todos:
        markinhos_on = True
        sinal_on = False
        agradecimentos_on = True

    if markinhos_on:
        print("\n\n")
        print(colored("                  ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠿⠿⠿⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿","red"))
        print(colored("                  ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⣉⣁⣤⣤⣶⣾⣿⣿⣶⡄⢲⣯⢍⠁⠄⢀⢹⣿⣿","red"))
        print(colored("                  ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢯⣾⣿⣿⣏⣉⣹⠿⠇⠄⠽⠿⢷⡈⠿⠇⣀⣻⣿⡿⣻⣿","red"))
        print(colored("                  ⣿⣿⣿⡿⠿⠛⠛⠛⢛⡃⢉⢣⡤⠤⢄⡶⠂⠄⠐⣀⠄⠄⠄⠄⠄⡦⣿⡿⠛⡇⣼⣿","red"))
        print(colored("                  ⣿⡿⢫⣤⣦⠄⠂⠄⠄⠄⠄⠄⠄⠄⠄⠠⠺⠿⠙⠋⠄⠄⠄⠢⢄⠄⢿⠇⠂⠧⣿⣿","red"))
        print(colored("                  ⣿⠁⠄⠈⠁⠄⢀⣀⣀⣀⣀⣠⣤⡤⠴⠖⠒⠄⠄⠄⠄⠄⠄⠄⠄⠄⠘⢠⡞⠄⣸⣿","red"))
        print(colored("                  ⣿⡀⠄⠄⠄⠄⠄⠤⠭⠦⠤⠤⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣂⣿⣿","red"))
        print(colored("                  ⣿⣷⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢳⠄⠄⢀⠈⣠⣤⣤⣼⣿⣿","red"))
        print(colored("                  ⣿⣿⣿⣷⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣴⣶⣶⣶⣄⡀⠄⠈⠑⢙⣡⣴⣿⣿⣿⣿⣿⣿","red"))
        print(colored("                  ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿","red"))
        print("\n")

    if markinhos_on: 
        print(colored("    _____  ______ _        //\   __  __ _____        _____  ____  ", "white"))
        time.sleep(time_regulado)
        print(colored("   |  __ \|  ____| |      |/_\| |  \/  |  __ \ /\   / ____|/ __ \ ", "white"))
        time.sleep(time_regulado)
        print(colored("   | |__) | |__  | |       / \  | \  / | |__) /  \ | |  __| |  | |", "white"))
        time.sleep(time_regulado)
        print(colored("   |  _  /|  __| | |      / _ \ | |\/| |  ___/ /\ \| | |_ | |  | |", "white"))
        time.sleep(time_regulado)
        print(colored("   | | \ \| |____| |____ / ___ \| |  | | |  / ____ \ |__| | |__| |", "white"))
        time.sleep(time_regulado)
        print(colored("   |_|  \_\______|______/_/   \_\_|  |_|_| /_/    \_\_____|\____/ ", "white"))
        time.sleep(time_regulado)
        print(colored("    __  __          _____  _  _______ _   _ _    _  ____   _____ ", "red"))
        time.sleep(time_regulado)
        print(colored("   |  \/  |   /\   |  __ \| |/ /_   _| \ | | |  | |/ __ \ / ____|", "red"))
        time.sleep(time_regulado)
        print(colored("   | \  / |  /  \  | |__) | ' /  | | |  \| | |__| | |  | | (___  ", "red"))
        time.sleep(time_regulado)
        print(colored("   | |\/| | / /\ \ |  _  /|  <   | | | . ` |  __  | |  | |\___ \ ", "red"))
        time.sleep(time_regulado)
        print(colored("   | |  | |/ ____ \| | \ \| . \ _| |_| |\  | |  | | |__| |____) |", "red"))
        time.sleep(time_regulado)
        print(colored("   |_|  |_/_/    \_\_|  \_\_|\_\_____|_| \_|_|  |_|\____/|_____/ ", "red"))
        time.sleep(time_regulado)

    if sinal_on:
        print("\n\n")
        time.sleep(time_regulado+0.4)
        print(colored("               ______       ","red"))
        print(colored("            .od$$$$$$bo.    ","red"))
        print(colored("          /d$$$$$$$$$$$$b\  ","red"))
        print(colored("         ;$$$$$$$$$$$$$$$$; ","red"))
        print(colored("        ;$$$$$$$$$$$$$$$$$$;","red"))
        print(colored("        ;$$$$$$$$$$$$$$$$$$;","red"))
        print(colored("         ;$$$$$$$$$$$$$$$$; ","red"))
        print(colored("          \$$$$$$$$$$$$$$/  ","red"))
        print(colored("            '.$$$$$$$$$.'   ","red"))
        print("\n\n")                               
        time.sleep(time_regulado+0.4)
        print(colored("               ______       ","yellow"))
        print(colored("            .od$$$$$$bo.    ","yellow"))
        print(colored("          /d$$$$$$$$$$$$b\  ","yellow"))
        print(colored("         ;$$$$$$$$$$$$$$$$; ","yellow"))
        print(colored("        ;$$$$$$$$$$$$$$$$$$;","yellow"))
        print(colored("        ;$$$$$$$$$$$$$$$$$$;","yellow"))
        print(colored("         ;$$$$$$$$$$$$$$$$; ","yellow"))
        print(colored("          \$$$$$$$$$$$$$$/  ","yellow"))
        print(colored("            '.$$$$$$$$$.'   ","yellow"))
        print("\n\n")                             
        time.sleep(time_regulado+0.4)
        print(colored("               ______       ","green"))
        print(colored("            .od$$$$$$bo.    ","green"))
        print(colored("          /d$$$$$$$$$$$$b\  ","green"))
        print(colored("         ;$$$$$$$$$$$$$$$$; ","green"))
        print(colored("        ;$$$$$$$$$$$$$$$$$$;","green"))
        print(colored("        ;$$$$$$$$$$$$$$$$$$;","green"))
        print(colored("         ;$$$$$$$$$$$$$$$$; ","green"))
        print(colored("          \$$$$$$$$$$$$$$/  ","green"))
        print(colored("            '.$$$$$$$$$.'   ","green"))
        print("\n\n")
        time.sleep(time_regulado)                             
        print(colored("             GGGGGGGGGGGGG     OOOOOOOOO        !!! ","red"))
        print(colored("          GGG::::::::::::G   OO:::::::::OO     !!:!!","red"))
        print(colored("        GG:::::::::::::::G OO:::::::::::::OO   !:::!","red"))
        print(colored("       G:::::GGGGGGGG::::GO:::::::OOO:::::::O  !:::!","red"))
        print(colored("      G:::::G       GGGGGGO::::::O   O::::::O  !:::!","red"))
        print(colored("     G:::::G              O:::::O     O:::::O  !:::!","red"))
        print(colored("     G:::::G              O:::::O     O:::::O  !:::!","red"))
        print(colored("     G:::::G    GGGGGGGGGGO:::::O     O:::::O  !:::!","red"))
        print(colored("     G:::::G    G::::::::GO:::::O     O:::::O  !:::!","red"))
        print(colored("     G:::::G    GGGGG::::GO:::::O     O:::::O  !:::!","red"))
        print(colored("     G:::::G        G::::GO:::::O     O:::::O  !!:!!","red"))
        print(colored("      G:::::G       G::::GO::::::O   O::::::O   !!! ","red"))
        print(colored("       G:::::GGGGGGGG::::GO:::::::OOO:::::::O       ","red"))
        print(colored("        GG:::::::::::::::G OO:::::::::::::OO    !!! ","red"))
        print(colored("          GGG::::::GGG:::G   OO:::::::::OO     !!:!!","red"))
        print(colored("             GGGGGG   GGGG     OOOOOOOOO        !!! ","red"))
    
    if agradecimentos_on:
        print("\n")
        print(colored("      Mecânicos: Davi Reis, Francisco Janela e Nicolas Queiroga.","green"))
        time.sleep(time_regulado)
        print(colored(" Engenheiros: Fábio Miranda, Lícia Sales, Arnaldo Junior e Diego Pavan.","white"))
        time.sleep(time_regulado)

    print("\n")
    print("      -----------------------OBJETIVO:-------------------------")
    print(f'                      - Cor do Creeper: {objetivo[0]}')
    print(f'                      - ID do Creeper: {objetivo[1]}')
    print(f'                      - Estação Final: {objetivo[2]}')
    print("      ---------------------------------------------------------")
    print("\n")
    print(colored("      ---------------------------------------------------------","red"))
    print(colored("      |        Informações Vitais do Relâmpago Markinhos:     |","white"))
    print(colored("      ---------------------------------------------------------","red"))
    print("\n")

def encerrar_missao():
    print("\n                               KACHAU!                  \n")
    print(colored('                    zeeeeee-                  zeeeeee- ','yellow'))
    print(colored('                   z$$$$$$"                  z$$$$$$" ','yellow'))
    print(colored('                  d$$$$$$"                  d$$$$$$" ','yellow'))
    print(colored('                 d$$$$$P                   d$$$$$P ','yellow'))
    print(colored('                d$$$$$P                   d$$$$$P ','yellow'))
    print(colored('               $$$$$$"                   $$$$$$" ','yellow'))
    print(colored('             .$$$$$$"                  .$$$$$$" ','yellow'))
    print(colored('            .$$$$$$"                  .$$$$$$" ','yellow'))
    print(colored('           4$$$$$$$$$$$$$"           4$$$$$$$$$$$$$" ','yellow'))
    print(colored('          z$$$$$$$$$$$$$"           z$$$$$$$$$$$$$" ','yellow'))
    print(colored('          """""""3$$$$$"            """""""3$$$$$" ','yellow'))
    print(colored('                z$$$$P                    z$$$$P ','yellow'))
    print(colored('               d$$$$"                    d$$$$" ','yellow'))
    print(colored('             .$$$$$"                   .$$$$$" ','yellow'))
    print(colored('            z$$$$$"                   z$$$$$" ','yellow'))
    print(colored('           z$$$$P                    z$$$$P ','yellow'))
    print(colored('          d$$$$$$$$$$"              d$$$$$$$$$$" ','yellow'))
    print(colored('         *******$$$"               *******$$$" ','yellow'))
    print(colored('              .$$$"                     .$$$" ','yellow'))
    print(colored('             .$$"                      .$$" ','yellow'))
    print(colored('            4$P"                      4$P" ','yellow'))
    print(colored('           z$"                       z$" ','yellow'))
    print(colored('          zP                        zP ','yellow'))
    print(colored('         z"                        z" ','yellow'))
    print(colored('        /                         /   ','yellow'))
    print("\n")
    print(colored("------------------------ATENÇÃO:-------------------------","red"))
    print(colored("|         Relâmpago Markinhos foi para o PitStop!       |","red"))
    print(colored("---------------------------------------------------------","red"))