#! /usr/bin/env python3
# -*- coding:utf-8 -*-
from relampago_markinhos import *

goal1 = ("blue", 22, "dog")
goal2 = ("pink", 13, "bird")
goal3 = ("orange", 11, "cat")
                                                    
def logo_relampago_markinhos():
    time_regulado = 0.1

    print("          _____                    _____                    _____          ")
    print("         /\    \                  /\    \                  /\    \         ")
    print("        /::\    \                /::\____\                /::\    \        ")
    print("        \:::\    \              /::::|   |               /::::\    \       ")
    print("         \:::\    \            /:::::|   |              /::::::\    \      ")
    print("          \:::\    \          /::::::|   |             /:::/\:::\    \     ")
    print("           \:::\    \        /:::/|::|   |            /:::/__\:::\    \    ")
    print("           /::::\    \      /:::/ |::|   |            \:::\   \:::\    \   ")
    print("  ____    /::::::\    \    /:::/  |::|   | _____    ___\:::\   \:::\    \  ")
    print(" /\   \  /:::/\:::\    \  /:::/   |::|   |/\    \  /\   \:::\   \:::\    \ ")
    print("/::\   \/:::/  \:::\____\/:: /    |::|   /::\____\/::\   \:::\   \:::\____\ ")
    print("\:::\  /:::/    \::/    /\::/    /|::|  /:::/    /\:::\   \:::\   \::/    /")
    print(" \:::\/:::/    / \/____/  \/____/ |::| /:::/    /  \:::\   \:::\   \/____/ ")
    print("  \::::::/    /                   |::|/:::/    /    \:::\   \:::\    \     ")
    print("   \::::/____/                    |::::::/    /      \:::\   \:::\____\    ")
    print("    \:::\    \                    |:::::/    /        \:::\  /:::/    /    ")
    print("     \:::\    \                   |::::/    /          \:::\/:::/    /     ")
    print("      \:::\    \                  /:::/    /            \::::::/    /      ")
    print("       \:::\____\                /:::/    /              \::::/    /       ")
    print("        \::/    /                \::/    /                \::/    /        ")
    print("         \/____/                  \/____/                  \/____/         ")
    print("                                                                           ")
    time.sleep(time_regulado+0.4)
    print("          _____                    _____                    _____          ")
    print("         /\    \                  /\    \                  /\    \         ")
    print("        /::\    \                /::\    \                /::\    \        ")
    print("       /::::\    \              /::::\    \              /::::\    \       ")
    print("      /::::::\    \            /::::::\    \            /::::::\    \      ")
    print("     /:::/\:::\    \          /:::/\:::\    \          /:::/\:::\    \     ")
    print("    /:::/__\:::\    \        /:::/__\:::\    \        /:::/__\:::\    \    ")
    print("   /::::\   \:::\    \      /::::\   \:::\    \      /::::\   \:::\    \   ")
    print("  /::::::\   \:::\    \    /::::::\   \:::\    \    /::::::\   \:::\    \  ")
    print(" /:::/\:::\   \:::\____\  /:::/\:::\   \:::\    \  /:::/\:::\   \:::\____\ ")
    print("/:::/  \:::\   \:::|    |/:::/__\:::\   \:::\____\/:::/  \:::\   \:::|    |")
    print("\::/    \:::\  /:::|____|\:::\   \:::\   \::/    /\::/   |::::\  /:::|____|")
    print(" \/_____/\:::\/:::/    /  \:::\   \:::\   \/____/  \/____|:::::\/:::/    / ")
    print("          \::::::/    /    \:::\   \:::\    \            |:::::::::/    /  ")
    print("           \::::/    /      \:::\   \:::\____\           |::|\::::/    /   ")
    print("            \::/____/        \:::\   \::/    /           |::| \::/____/    ")
    print("             ~~               \:::\   \/____/            |::|  ~|          ")
    print("                               \:::\    \                |::|   |          ")
    print("                                \:::\____\               \::|   |          ")
    print("                                 \::/    /                \:|   |          ")
    print("                                  \/____/                  \|___|          ")
    time.sleep(time_regulado+0.8)
    print("\n\n")
    print(" _____  ______ _        //\   __  __ _____        _____  ____  ")
    time.sleep(time_regulado)
    print("|  __ \|  ____| |      |/_\| |  \/  |  __ \ /\   / ____|/ __ \ ")
    time.sleep(time_regulado)
    print("| |__) | |__  | |       / \  | \  / | |__) /  \ | |  __| |  | |")
    time.sleep(time_regulado)
    print("|  _  /|  __| | |      / _ \ | |\/| |  ___/ /\ \| | |_ | |  | |")
    time.sleep(time_regulado)
    print("| | \ \| |____| |____ / ___ \| |  | | |  / ____ \ |__| | |__| |")
    time.sleep(time_regulado)
    print("|_|  \_\______|______/_/   \_\_|  |_|_| /_/    \_\_____|\____/ ")
    time.sleep(time_regulado)
    print(" __  __          _____  _  _______ _   _ _    _  ____   _____ ")
    time.sleep(time_regulado)
    print("|  \/  |   /\   |  __ \| |/ /_   _| \ | | |  | |/ __ \ / ____|")
    time.sleep(time_regulado)
    print("| \  / |  /  \  | |__) | ' /  | | |  \| | |__| | |  | | (___  ")
    time.sleep(time_regulado)
    print("| |\/| | / /\ \ |  _  /|  <   | | | . ` |  __  | |  | |\___ \ ")
    time.sleep(time_regulado)
    print("| |  | |/ ____ \| | \ \| . \ _| |_| |\  | |  | | |__| |____) |")
    time.sleep(time_regulado)
    print("|_|  |_/_/    \_\_|  \_\_|\_\_____|_| \_|_|  |_|\____/|_____/ ")
    time.sleep(time_regulado)
    print("\n\n                         KACHAU...               \n")
    print("                            __")
    print("                            \ \ ")
    print("                             \ \ ")
    print("                            __\ \ ")
    print("                            \  __\ ")
    print("                             \ \ ")
    print("                              \ \ ")
    print("                               \/")
    time.sleep(time_regulado)
    print("\n\n  Mecânicos: Davi Reis, Francisco Janela e Nicolas Queiroga.")
    time.sleep(time_regulado)
    print("\n\n  Patrocinadores: Fábio Miranda, Lícia Sales, Arnaldo Junior e Diego Pavan.")
    time.sleep(time_regulado)

                                                                                   
                                                                
if __name__ == "__main__":
    logo_relampago_markinhos()
    #relampagoMarkinhos(objetivo, Conceito_C)
    relampagoMarkinhos(goal1, True)


